server.port=8080

spring.profiles.active=dev

# load .env automatically
spring.config.import=optional:dotenv:

app.base-url=${APP_BASE_URL}

# --- JWT Security Configuration ---
# Move secret key and expiration to environment variables
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=https

# Database Config
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# HikariCP Connection Pool
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST}
spring.mail.properties.mail.smtp.ssl.checkserveridentity=true

#  endpoints
resilience4j.ratelimiter.instances.shortenRateLimiter.limit-for-period=20
resilience4j.ratelimiter.instances.shortenRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.shortenRateLimiter.timeout-duration=0